[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "theme-inheritance"
version = "1.0"

[project.entry-points]
"sphinx.html_themes" = { inherited_theme = "inherited_theme" }
